### ISSUE TITLE
[Suggestion] New Logo for Book Base

### ISSUE THREAD

**Issue by zularizal** [lachlan-eagling/Bookbase#14]
Hi, I want to contribute to this project, I want to create a new logo and icon for your project and it's free, do you want it?

**Comment by lachlan-eagling** [comment]
Hi @zularizal,

Firstly thank you for interest in contributing to my project.

I would like to see what you have in mind for a new logo/icon. If you are able to share it with me I will take your contribution into consideration.

**Comment by zularizal** [comment]
What do you think? I made it simple with the color of the material design. Is there anything I need to change it?

![logo](https://user-images.githubusercontent.com/38547278/39789543-bba8c99e-535a-11e8-87b0-4c81a6b02691.png)

**Comment by zularizal** [comment]
Hi, @lachlan-eagling What do you think about this?

**Comment by lachlan-eagling** [comment]
Hi @zularizal 

Apologies about the delayed response. I like the look of the logo however would prefer to stick with the current colour theme of the app (dark grey with the orange primary colour).

**Comment by zularizal** [comment]
Hi @lachlan-eagling , how about this?

![bitmap](https://user-images.githubusercontent.com/38547278/41641164-92cddf8c-748e-11e8-8d27-22e717ff1a1f.png)

**Comment by lachlan-eagling** [comment]
Perfect, love this one. Are you able to create a new branch for this and update the color & drawable resources in the app then submit a pull request? Alternatively I can make these changes if you are able to supply the files files and exact hex color codes used.

**Comment by zularizal** [comment]
Hi @lachlan-eagling , I have uploaded the logo to drive, you can check it in this link.
https://drive.google.com/open?id=1Vsco5DfcAhKcPeDkovTR7hFwqkeY-Qqw

And also I have sent pull request for you check #18
